### ISSUE TITLE
zpm install doesn't work

### ISSUE THREAD

**Issue by grongierisc** [yurimarx/automl-heart#2]
zpm install doesn't work on another container than the one in this repository : 
IRISAPP>zpm "install dataset-health"

[sslclient]     Reload START (/usr/irissys/mgr/.modules/IRISAPP/sslclient/1.0.4/)
[sslclient]     Reload SUCCESS
[sslclient]     Module object refreshed.
[sslclient]     Validate START
[sslclient]     Validate SUCCESS
[sslclient]     Compile START
[sslclient]     Compile SUCCESS
[sslclient]     Activate START
[sslclient]     Configure START
[sslclient]     Configure SUCCESS
[sslclient]     MakeDeployed START
[sslclient]     MakeDeployed SUCCESS
[sslclient]     Activate SUCCESS
[csvgen]        Reload START (/usr/irissys/mgr/.modules/IRISAPP/csvgen/1.2.1/)
[csvgen]        Reload SUCCESS
[csvgen]        Module object refreshed.
[csvgen]        Validate START
[csvgen]        Validate SUCCESS
[csvgen]        Compile START
[csvgen]        Compile SUCCESS
[csvgen]        Activate START
[csvgen]        Configure START
[csvgen]        Configure SUCCESS
[csvgen]        MakeDeployed START
[csvgen]        MakeDeployed SUCCESS
[csvgen]        Activate SUCCESS
[dataset-health]        Reload START (/usr/irissys/mgr/.modules/IRISAPP/dataset-health/1.2.0/)
[dataset-health]        Reload SUCCESS
[dataset-health]        Module object refreshed.
[dataset-health]        Validate START
[dataset-health]        Validate SUCCESS
[dataset-health]        Compile START
[dataset-health]        Compile SUCCESS
[dataset-health]        Activate START
[dataset-health]        Configure START
Load of directory started on 01/13/2022 09:31:18
ERROR #5007: Directory name '/opt/irisapp/src/dc/data/health' is invalid
Detected 1 errors during load.

[dataset-health]        Configure SUCCESS
[dataset-health]        Activate FAILURE
ERROR! Module 'dataset-health' not found.

**Comment by yurimarx** [comment]
I fixed this already, but the zpm repository remains with the old version. I sent a new package version to publication now. I will send you a message to try again, when they publish the new version

**Comment by yurimarx** [comment]
Fixed in the new version. Can you try again? Thanks!

**Comment by grongierisc** [comment]
Confirmed, it's fixed !
